---
title: "NYCDSA Project2 - The Impact of Cryptocurrency on Global Economic Stability"
output: html_notebook
---

Generate plot of cryptocurrency market capitalisation since April 2020. I have only been able to obtain data for Bitcoin (not yet for other currencies).

```{r}
library(Quandl)
library(ggplot2)
library(tidyr)
library(dplyr)
library(tidyquant)
library(patchwork)

path = "~/Desktop/NYCDSA/Homework/Project2"
setwd(path)

Mktcp_Start = as.Date("2020-04-01")
Mktcp_End = as.Date("2022-02-11")

Bitcoin_Mktcp = Quandl("BCHAIN/MKTCP", start_date=Mktcp_Start, end_date=Mktcp_End)

head(Bitcoin_Mktcp)

ETH_Mktcp = read.csv("ETH.csv")

BNB_Mktcp = read.csv("BNB.csv")

SPY = tq_get('^GSPC',
             from = Mktcp_Start,
             to = Mktcp_End,
             get = "stock.prices"
             )

Bitcoin_Mktcp_Scaled = Bitcoin_Mktcp

ETH_Mktcp_Scaled = ETH_Mktcp

BNB_Mktcp_Scaled = BNB_Mktcp

names(ETH_Mktcp_Scaled)[names(ETH_Mktcp_Scaled) == 'Circulating.Marketcap'] = 'ETH.MC'

names(BNB_Mktcp_Scaled)[names(BNB_Mktcp_Scaled) == 'Circulating.Marketcap'] = 'BNB.MC'

SPY.df = data.frame(SPY$date, SPY$close)

ETH_Mktcp_Scaled$Date <- as.Date(ETH_Mktcp_Scaled$Date, format = "%Y-%m-%d")

BNB_Mktcp_Scaled$Date <- as.Date(BNB_Mktcp_Scaled$Date, format = "%Y-%m-%d")

head(ETH_Mktcp_Scaled, n=60)

Bitcoin_Mktcp_Scaled$Value = Bitcoin_Mktcp_Scaled$Value / 1E12

ETH_Mktcp_Scaled$ETH.MC = ETH_Mktcp_Scaled$ETH.MC / 1E12

BNB_Mktcp_Scaled$BNB.MC = BNB_Mktcp_Scaled$BNB.MC / 1E12

Bitcoin_Mktcp_Scaled = merge(Bitcoin_Mktcp_Scaled, SPY.df, by.x = "Date", by.y = "SPY.date")

Bitcoin_Mktcp_Scaled = merge(Bitcoin_Mktcp_Scaled, ETH_Mktcp_Scaled, by="Date")

Bitcoin_Mktcp_Scaled = merge(Bitcoin_Mktcp_Scaled, BNB_Mktcp_Scaled, by="Date")

head(Bitcoin_Mktcp_Scaled, n=200)

coeff = 5000

cols = c("S&P500" = "red", "Bitcoin (BTC)" = "#00AFBB", "Ethereum (ETH)" = "#E7B800", "Binance (BNB)" = "#FFCCFF")

ggplot(Bitcoin_Mktcp_Scaled, aes(x=Date)) + 
  geom_area(aes(y = Value, fill = "Bitcoin (BTC)"), 
            colour = "#00AFBB", alpha=0.5) + 
  geom_area(aes(y = ETH.MC, fill = "Ethereum (ETH)"), 
            colour = "#E7B800", alpha=0.5) + 
  geom_area(aes(y = BNB.MC, fill = "Binance (BNB)"), 
            colour = "#FFCCFF", alpha=0.5) +
  labs(title="Cryptocurrency Market Capitalisation",
        x ="Date", y = "Crypto Market Capitalisation \n (US$ trillion)") +
  theme(axis.text = element_text(face="bold")) +
  theme(axis.title = element_text(face="bold")) +
  theme(plot.title = element_text(face="bold", hjust = 0.5)) +
  geom_line(aes(y=SPY.close / coeff, colour = "S&P500"), linetype = "solid") +
  scale_colour_manual(name = '', values=cols, 
                      guide = guide_legend(override.aes=aes(fill=NA))) +
  scale_fill_manual(values=cols, guide="none") +
  scale_y_continuous(
    sec.axis = sec_axis(~.*coeff, name="S&P500, Price (US$)")
  ) +
  theme(
    legend.position = c(.275, 1.09),
    legend.justification = c("right", "top"),
    legend.box.just = "right",
    legend.margin = margin(6, 6, 6, 6)
    )
  
ggsave("fig1.png")


#coord_cartesian(xlim = c(Mktcp_Start, Mktcp_End))
#, "#E7B800"
#, "#E7B800"
#mydata = Quandl("FRED/GDP", type="raw")

#mydata = Quandl("FRED/GDP", start_date="2001-12-31", end_date="2005-12-31")

#mydata = Quandl(c("FRED/GDP.1", "WIKI/AAPL.4"))

#Quandl("BCHAIN/MKTCP")

#Quandl("FRED/TEDRATE")

```



```{r}
library(Quandl)
library(ggplot2)
library(tidyr)
library(dplyr)
library(tidyquant)
library(patchwork)
library(tidyverse)
library(latex2exp)

Vol_Start = "2014-07-01"
Vol_End = "2022-02-11"
Covid_19 = as.Date("2020-03-01")

window = 30

tickers1 = c('^GSPC', '^IXIC', '^GDAXI', '^FTSE', '^N225', '^DJI',
             'BTC-USD', 'ETH-USD', 'BNB-USD', 'ADA-USD', 'SOL-USD', 'XRP-USD')

TED = Quandl("FRED/TEDRATE", start_date=Vol_Start, end_date=Vol_End)

colnames(TED)[1] = "date"
colnames(TED)[2] = "TED"

TED = as.data.frame(TED)

head(TED)

GSPC = tq_get(tickers1[1],
             from = Vol_Start,
             to = Vol_End,
             get = "stock.prices"
             ) %>%
        tq_transmute(adjusted, periodReturn, period = "daily", type = "log", col_rename = c("GSPC.logret"))

head(GSPC)

GSPC = GSPC %>%
  tq_mutate(select = GSPC.logret,
            mutate_fun = rollapply,
            width = window,
            FUN = sd,
            na.rm = TRUE,
            col_rename = "GSPC.volatility")

IXIC = tq_get(tickers1[2],
             from = Vol_Start,
             to = Vol_End,
             get = "stock.prices"
             ) %>%
        tq_transmute(adjusted, periodReturn, period = "daily", type = "log", col_rename = c("IXIC.logret"))

IXIC = IXIC %>%
  tq_mutate(select = IXIC.logret,
            mutate_fun = rollapply,
            width = window,
            FUN = sd,
            na.rm = TRUE,
            col_rename = "IXIC.volatility")

FTSE = tq_get(tickers1[4],
             from = Vol_Start,
             to = Vol_End,
             get = "stock.prices"
             ) %>%
        tq_transmute(adjusted, periodReturn, period = "daily", type = "log", col_rename = c("FTSE.logret"))

FTSE = FTSE %>%
  tq_mutate(select = FTSE.logret,
            mutate_fun = rollapply,
            width = window,
            FUN = sd,
            na.rm = TRUE,
            col_rename = "FTSE.volatility")

BTC = tq_get(tickers1[7],
             from = Vol_Start,
             to = Vol_End,
             get = "stock.prices"
             ) %>%
        tq_transmute(adjusted, periodReturn, period = "daily", type = "log", col_rename = c("BTC.logret"))

BTC = BTC %>%
  tq_mutate(select = BTC.logret,
            mutate_fun = rollapply,
            width = window,
            FUN = sd,
            na.rm = TRUE,
            col_rename = "BTC.volatility")

ETH = tq_get(tickers1[8],
             from = Vol_Start,
             to = Vol_End,
             get = "stock.prices"
             ) %>%
        tq_transmute(adjusted, periodReturn, period = "daily", type = "log", col_rename = c("ETH.logret"))

ETH = ETH %>%
  tq_mutate(select = ETH.logret,
            mutate_fun = rollapply,
            width = window,
            FUN = sd,
            na.rm = TRUE,
            col_rename = "ETH.volatility")

BNB = tq_get(tickers1[9],
             from = Vol_Start,
             to = Vol_End,
             get = "stock.prices"
             ) %>%
        tq_transmute(adjusted, periodReturn, period = "daily", type = "log", col_rename = c("BNB.logret"))

BNB = BNB %>%
  tq_mutate(select = BNB.logret,
            mutate_fun = rollapply,
            width = window,
            FUN = sd,
            na.rm = TRUE,
            col_rename = "BNB.volatility")

# Put all data frames into list
Volatility_List = list(GSPC, IXIC, FTSE, BTC, ETH, BNB)

# Merge all data frames in list
Volatility_List = Volatility_List %>% 
  reduce(full_join, by='date')

Volatility_List = as.data.frame(Volatility_List)

Volatility_List = Volatility_List %>% full_join(TED,by="date")

colours = c("GSPC" = "#0080FF", "FTSE" = "#FF9933", "BTC" = "#CC99FF", "ETH" = "#9999FF", "TED" = "red")

scaler = 10

ggplot(Volatility_List, aes(x=date)) +
  geom_line(aes(y=GSPC.volatility, colour="GSPC"), linetype="dashed") +
  geom_line(aes(y=FTSE.volatility, colour="FTSE"), linetype="dashed") +
  geom_line(aes(y=BTC.volatility, colour="BTC"), linetype="solid") +
  geom_line(aes(y=ETH.volatility, colour="ETH"), linetype="solid") +
  geom_line(aes(y=TED / scaler, colour = "TED"), linetype = 4) +
  labs(title="Volatility - Cryptocurrency vs Markets",
        x ="Date", y = TeX("$\\bold(Volatility)~~(\\sigma (\\log \\[\\italic(return) \\] ))$"), color = "Tickers") +
  theme(axis.text = element_text(face="bold")) +
  theme(axis.title = element_text(face="bold")) +
  theme(plot.title = element_text(face="bold", hjust = 0.5)) +
  scale_y_continuous(
    sec.axis = sec_axis(~.*scaler, name="TED Spread")
  ) +
  scale_color_manual(values = colours) +
  annotate(geom = "vline",
           x = Covid_19,
           xintercept = Covid_19,
           linetype = "dashed",
           size=0.5) +
  annotate(geom = "text",
           label = "Covid-19 ",
           x = Covid_19,
           y = 0.15,
           angle = 0,
           hjust=1)

ggsave("fig2.png")

```


```{r}

Entropy_Start = as.Date("2018-01-01")
Entropy_End = as.Date("2022-02-11")

tickers2 = c('^GSPC', '^IXIC', '^GDAXI', '^FTSE', '^N225', '^DJI',
             'BTC-USD', 'ETH-USD', 'BNB-USD', 'ADA-USD', 'SOL-USD', 'XRP-USD')

GSPC = tq_get(tickers2[1],
             from = Entropy_Start,
             to = Entropy_End,
             get = "stock.prices"
             ) %>%
  select(date, adjusted) %>%
  rename(GSPC = adjusted)

head(GSPC)

IXIC = tq_get(tickers2[2],
             from = Entropy_Start,
             to = Entropy_End,
             get = "stock.prices"
             ) %>%
  select(date, adjusted) %>%
  rename(IXIC = adjusted)

GDAXI = tq_get(tickers2[3],
             from = Entropy_Start,
             to = Entropy_End,
             get = "stock.prices"
             ) %>%
  select(date, adjusted) %>%
  rename(GDAXI = adjusted)

FTSE = tq_get(tickers2[4],
             from = Entropy_Start,
             to = Entropy_End,
             get = "stock.prices"
             ) %>%
  select(date, adjusted) %>%
  rename(FTSE = adjusted)

N225 = tq_get(tickers2[5],
             from = Entropy_Start,
             to = Entropy_End,
             get = "stock.prices"
             ) %>%
  select(date, adjusted) %>%
  rename(N225 = adjusted)

DJI = tq_get(tickers2[6],
             from = Entropy_Start,
             to = Entropy_End,
             get = "stock.prices"
             ) %>%
  select(date, adjusted) %>%
  rename(DJI = adjusted)

BTC = tq_get(tickers2[7],
             from = Entropy_Start,
             to = Entropy_End,
             get = "stock.prices"
             ) %>%
  select(date, adjusted) %>%
  rename(BTC = adjusted)

ETH = tq_get(tickers2[8],
             from = Entropy_Start,
             to = Entropy_End,
             get = "stock.prices"
             ) %>%
  select(date, adjusted) %>%
  rename(ETH = adjusted)

BNB = tq_get(tickers2[9],
             from = Entropy_Start,
             to = Entropy_End,
             get = "stock.prices"
             ) %>%
  select(date, adjusted) %>%
  rename(BNB = adjusted)

ADA = tq_get(tickers2[10],
             from = Entropy_Start,
             to = Entropy_End,
             get = "stock.prices"
             ) %>%
  select(date, adjusted) %>%
  rename(ADA = adjusted)

SOL = tq_get(tickers2[11],
             from = Entropy_Start,
             to = Entropy_End,
             get = "stock.prices"
             ) %>%
  select(date, adjusted) %>%
  rename(SOL = adjusted)

XRP = tq_get(tickers2[12],
             from = Entropy_Start,
             to = Entropy_End,
             get = "stock.prices"
             ) %>%
  select(date, adjusted) %>%
  rename(XRP = adjusted)

DF = list(GSPC, IXIC, GDAXI, FTSE, N225, DJI, BTC, ETH, BNB, ADA, SOL, XRP)  %>% reduce(inner_join, by = "date")

DF = DF %>% drop_na()

DF = as.data.frame(DF)

rownames(DF) = DF$date

head(DF)

DF_temp = subset(DF, select=-1)

head(DF_temp)

vn_entropy = function(dframe){
  my_matrix = data.matrix(dframe)
  my_corr = cor(my_matrix, use="complete.obs", method="pearson")
  rho = my_corr/12
  neumann = rho%*%log(rho)
  return(-sum(diag(neumann)))
}

Entropy_DF = rollapply(DF_temp, 30, vn_entropy)

head(Entropy_DF, n=60)

```



```{r}

library(ggcorrplot)
library(qgraph)

Early_Start = as.Date("2019-05-01")
Early_End = as.Date("2020-05-01")

tickers2 = c('^GSPC', '^IXIC', '^GDAXI', '^FTSE', '^N225', '^DJI',
             'BTC-USD', 'ETH-USD', 'BNB-USD', 'ADA-USD', 'SOL-USD', 'XRP-USD')

GSPC = tq_get(tickers2[1],
             from = Early_Start,
             to = Early_End,
             get = "stock.prices"
             ) %>%
        tq_transmute(adjusted, periodReturn, period = "daily", type = "log", col_rename = c("GSPC"))

IXIC = tq_get(tickers2[2],
             from = Early_Start,
             to = Early_End,
             get = "stock.prices"
             ) %>%
        tq_transmute(adjusted, periodReturn, period = "daily", type = "log", col_rename = c("IXIC"))

GDAXI = tq_get(tickers2[3],
             from = Early_Start,
             to = Early_End,
             get = "stock.prices"
             ) %>%
        tq_transmute(adjusted, periodReturn, period = "daily", type = "log", col_rename = c("GDAXI"))

FTSE = tq_get(tickers2[4],
             from = Early_Start,
             to = Early_End,
             get = "stock.prices"
             ) %>%
        tq_transmute(adjusted, periodReturn, period = "daily", type = "log", col_rename = c("FTSE"))

N225 = tq_get(tickers2[5],
             from = Early_Start,
             to = Early_End,
             get = "stock.prices"
             ) %>%
        tq_transmute(adjusted, periodReturn, period = "daily", type = "log", col_rename = c("N225"))

DJI = tq_get(tickers2[6],
             from = Early_Start,
             to = Early_End,
             get = "stock.prices"
             ) %>%
        tq_transmute(adjusted, periodReturn, period = "daily", type = "log", col_rename = c("DJI"))

BTC = tq_get(tickers2[7],
             from = Early_Start,
             to = Early_End,
             get = "stock.prices"
             ) %>%
        tq_transmute(adjusted, periodReturn, period = "daily", type = "log", col_rename = c("BTC"))

ETH = tq_get(tickers2[8],
             from = Early_Start,
             to = Early_End,
             get = "stock.prices"
             ) %>%
        tq_transmute(adjusted, periodReturn, period = "daily", type = "log", col_rename = c("ETH"))

BNB = tq_get(tickers2[9],
             from = Early_Start,
             to = Early_End,
             get = "stock.prices"
             ) %>%
        tq_transmute(adjusted, periodReturn, period = "daily", type = "log", col_rename = c("BNB"))

ADA = tq_get(tickers2[10],
             from = Early_Start,
             to = Early_End,
             get = "stock.prices"
             ) %>%
        tq_transmute(adjusted, periodReturn, period = "daily", type = "log", col_rename = c("ADA"))

SOL = tq_get(tickers2[11],
             from = Early_Start,
             to = Early_End,
             get = "stock.prices"
             ) %>%
        tq_transmute(adjusted, periodReturn, period = "daily", type = "log", col_rename = c("SOL"))

XRP = tq_get(tickers2[12],
             from = Early_Start,
             to = Early_End,
             get = "stock.prices"
             ) %>%
        tq_transmute(adjusted, periodReturn, period = "daily", type = "log", col_rename = c("XRP"))

DF = list(GSPC, IXIC, GDAXI, FTSE, N225, DJI, BTC, ETH, BNB, ADA, SOL, XRP)  %>% reduce(inner_join, by = "date")

DF = DF %>% drop_na()

DF = as.data.frame(DF)

rownames(DF) = DF$date

head(DF)

DF_temp = subset(DF, select=-1)

head(DF_temp)

Early_Corr = cor(DF_temp)

ggcorrplot(Early_Corr, method = "circle", title="Cryptocurrency/Stockmarket Correlation \n                    2018-2019")

ggsave("fig4.png")

nNode <- 12
set.seed(2)
png("fig5.png")
qgraph(Early_Corr, graph="glasso", layout="spring", sampleSize = nrow(DF_temp),
               vsize=7, cut=0, maximum=.45, border.width=1.5, layout.par = list(init = matrix(rnorm(nNode*2),nNode,2)), title="Crypto/Stock Network Correlation 2018-2019")
dev.off()


```


```{r}


library(ggcorrplot)
library("qgraph")

Late_Start = as.Date("2021-01-01")
Late_End = as.Date("2022-02-11")

tickers2 = c('^GSPC', '^IXIC', '^GDAXI', '^FTSE', '^N225', '^DJI',
             'BTC-USD', 'ETH-USD', 'BNB-USD', 'ADA-USD', 'SOL-USD', 'XRP-USD')

GSPC = tq_get(tickers2[1],
             from = Late_Start,
             to = Late_End,
             get = "stock.prices"
             ) %>%
        tq_transmute(adjusted, periodReturn, period = "daily", type = "log", col_rename = c("GSPC"))

IXIC = tq_get(tickers2[2],
             from = Late_Start,
             to = Late_End,
             get = "stock.prices"
             ) %>%
        tq_transmute(adjusted, periodReturn, period = "daily", type = "log", col_rename = c("IXIC"))

GDAXI = tq_get(tickers2[3],
             from = Late_Start,
             to = Late_End,
             get = "stock.prices"
             ) %>%
        tq_transmute(adjusted, periodReturn, period = "daily", type = "log", col_rename = c("GDAXI"))

FTSE = tq_get(tickers2[4],
             from = Late_Start,
             to = Late_End,
             get = "stock.prices"
             ) %>%
        tq_transmute(adjusted, periodReturn, period = "daily", type = "log", col_rename = c("FTSE"))

N225 = tq_get(tickers2[5],
             from = Late_Start,
             to = Late_End,
             get = "stock.prices"
             ) %>%
        tq_transmute(adjusted, periodReturn, period = "daily", type = "log", col_rename = c("N225"))

DJI = tq_get(tickers2[6],
             from = Late_Start,
             to = Late_End,
             get = "stock.prices"
             ) %>%
        tq_transmute(adjusted, periodReturn, period = "daily", type = "log", col_rename = c("DJI"))

BTC = tq_get(tickers2[7],
             from = Late_Start,
             to = Late_End,
             get = "stock.prices"
             ) %>%
        tq_transmute(adjusted, periodReturn, period = "daily", type = "log", col_rename = c("BTC"))

ETH = tq_get(tickers2[8],
             from = Late_Start,
             to = Late_End,
             get = "stock.prices"
             ) %>%
        tq_transmute(adjusted, periodReturn, period = "daily", type = "log", col_rename = c("ETH"))

BNB = tq_get(tickers2[9],
             from = Late_Start,
             to = Late_End,
             get = "stock.prices"
             ) %>%
        tq_transmute(adjusted, periodReturn, period = "daily", type = "log", col_rename = c("BNB"))

ADA = tq_get(tickers2[10],
             from = Late_Start,
             to = Late_End,
             get = "stock.prices"
             ) %>%
        tq_transmute(adjusted, periodReturn, period = "daily", type = "log", col_rename = c("ADA"))

SOL = tq_get(tickers2[11],
             from = Late_Start,
             to = Late_End,
             get = "stock.prices"
             ) %>%
        tq_transmute(adjusted, periodReturn, period = "daily", type = "log", col_rename = c("SOL"))

XRP = tq_get(tickers2[12],
             from = Late_Start,
             to = Late_End,
             get = "stock.prices"
             ) %>%
        tq_transmute(adjusted, periodReturn, period = "daily", type = "log", col_rename = c("XRP"))

DF = list(GSPC, IXIC, GDAXI, FTSE, N225, DJI, BTC, ETH, BNB, ADA, SOL, XRP)  %>% reduce(inner_join, by = "date")

DF = DF %>% drop_na()

DF = as.data.frame(DF)

rownames(DF) = DF$date

head(DF)

DF_temp = subset(DF, select=-1)

head(DF_temp)

Late_Corr = cor(DF_temp)

ggcorrplot(Late_Corr, method = "circle", title="Cryptocurrency/Stockmarket Correlation \n                    2021-2022")

ggsave("fig6.png")

nNode <- 12
set.seed(1)
png("fig7.png")
qgraph(Late_Corr, graph="glasso", layout="spring", sampleSize = nrow(DF_temp),
               vsize=7, cut=0, maximum=.45, border.width=1.5, layout.par = list(init = matrix(rnorm(nNode*2),nNode,2)), title="Crypto/Stock Network Correlation 2021-2022")
dev.off()


```


```{r}

l = Quandl("FRED/TEDRATE")

```

